import { useCallback, useEffect, useRef, useState } from 'react';
import { LoginScreen } from '../components/LoginScreen';
import { WaitingScreen } from '../components/WaitingScreen';
import { GameClient, uploadMedia } from './client';
import CardRewards from './CardRewards';
import { LiveTaskBoard } from './LiveTaskBoard';
import { validateTestApiBase } from '../testing/ruleSuite';
import './ability.css';

type Entry = Record<string, any>;
type Session = { token: string; role: string; teamId?: string; leader: boolean; accountId?: string };
const statusLabels: Record<string, string> = { AVAILABLE: '可使用', USED: '已使用', PENDING: '等待工作人员确认', AWAITING_ACK: '等待目标接收', ACTIVE: '生效中', AWAITING_REVIEW: '等待现场审核', DONE: '已结束', REJECTED: '已打回', CANCELLED: '已取消' };
const time = (milliseconds: number) => `${Math.floor(Math.max(0, milliseconds) / 60000)}:${String(Math.floor(Math.max(0, milliseconds) / 1000) % 60).padStart(2, '0')}`;
const sampleConfig = JSON.stringify({ tasks: Array.from({ length: 25 }, (_, i) => ({ id: `T${String(i + 1).padStart(2, '0')}`, title: '', brief: '', points: 5 })), boardRewards: [] }, null, 2);

function ProofMedia({ client, id }: { client: GameClient; id: string }) {
  const [url, setUrl] = useState(''); const [video, setVideo] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let closed = false; let blobUrl = ''; void client.media(id).then(blob => { if (!closed) { blobUrl = URL.createObjectURL(blob); setUrl(blobUrl); setVideo(blob.type.startsWith('video/')); } }).catch(error => { if (!closed) setError(String(error)); }); return () => { closed = true; if (blobUrl) URL.revokeObjectURL(blobUrl); }; }, [client, id]);
  return error ? <p role="alert">{error}</p> : url ? video ? <video className="ability-proof" src={url} controls playsInline /> : <a href={url} target="_blank" rel="noreferrer"><img className="ability-proof" src={url} alt="现场完成证据，点击查看原图" /></a> : <p>读取证据中…</p>;
}

function ReservePoolEditor({ view, run }: { view: Entry; run: (body: Entry) => Promise<void> }) {
  const [tasks, setTasks] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  return <section className="ability-surface"><h2>无中生有备用任务池</h2><p>当前 {view.reserveTasks?.length ?? 0} 项。填写棋盘之外的真实任务；已抽给同队的任务不会再次抽中。</p><details><summary>配置备用任务</summary><button onClick={() => setTasks(JSON.stringify(view.reserveTasks ?? [], null, 2))}>载入当前任务池</button><form onSubmit={event => { event.preventDefault(); try { const parsed = JSON.parse(tasks); setError(''); void run({ type: 'ability_reserve_configure', tasks: parsed, reason }); } catch { setError('请填写有效的 JSON 数组'); } }}><label>备用任务 JSON<textarea value={tasks} onChange={event => setTasks(event.target.value)} required placeholder={'[{"id":"EXTRA01","title":"任务名称","brief":"现场完成要求","points":5}]'} /></label><label>修改原因<input required value={reason} onChange={event => setReason(event.target.value)} /></label>{error ? <p role="alert">{error}</p> : null}<button disabled={!reason.trim() || !tasks.trim() || view.status === 'FINISHED'}>保存备用任务池</button></form></details></section>;
}

function UsePanel({ use, view, session, client, run }: { use: Entry; view: Entry; session: Session; client: GameClient; run: (body: Entry) => Promise<void> }) {
  const [text, setText] = useState(''); const [file, setFile] = useState<File | null>(null); const [participants, setParticipants] = useState<string[]>([]);
  const [reviewTeam, setReviewTeam] = useState(use.targets[0]); const [reason, setReason] = useState(''); const [counts, setCounts] = useState<Record<string, number>>({}); const [digits, setDigits] = useState(0);
  const [peer, setPeer] = useState(''); const [ownTask, setOwnTask] = useState(''); const [peerTask, setPeerTask] = useState(''); const [inTime, setInTime] = useState(false);
  const staff = session.role === 'staff'; const ownTarget = use.targets.includes(session.teamId); const active = use.status === 'ACTIVE';
  const remaining = use.startedAt == null ? use.definition.durationMs : use.definition.durationMs - (view.elapsedMs - use.startedAt);
  const members = (view.roster ?? []).filter((member: Entry) => member.teamId === (staff ? reviewTeam : session.teamId));
  const review = (result: string) => run({ type: 'ability_review', useId: use.id, teamId: reviewTeam, result, reason, counts: Object.fromEntries(members.map((member: Entry) => [member.id, counts[member.id] ?? 0])), verifiedDigits: digits, completedInTime: inTime });
  const evidence = use.evidence ?? [];
  return <article className={`ability-use ability-use--${use.status.toLowerCase()}`}>
    <div className="ability-use__heading"><span className="ability-number">{String(use.number).padStart(2, '0')}</span><div><h3>{use.definition.title}</h3><p>{statusLabels[use.status]} · {use.startedAt == null ? '接收后开始计时' : `剩余 ${time(remaining)}`}</p></div><span>{use.targets.map((id: string) => view.teamChoices?.find((team: Entry) => team.id === id)?.name ?? id).join(' / ')}</span></div>
    <p>{use.definition.description}</p>
    {use.returnPosition ? <p>返回目标：{use.returnPosition.latitude.toFixed(6)}, {use.returnPosition.longitude.toFixed(6)} · 历史记录 {new Date(use.returnPosition.receivedAt).toLocaleTimeString()} · 需要实际返回并现场确认</p> : null}
    {use.redoTask ? <p>重做 {use.redoTask.taskId} · 完成奖励 {use.redoTask.points / 2} 分</p> : null}
    {use.extraTask ? <section aria-label="随机额外任务"><h4>{use.extraTask.id} · {use.extraTask.title}</h4><p>{use.extraTask.brief}</p><p>请在本卡提交完成说明和现场图片或视频，等待工作人员审核。</p></section> : null}
    {active && use.number === 24 ? <p className="ability-alert">全员禁言中：只能使用手机打字交流。倒计时结束后解除，由工作人员核实期间是否违规。</p> : null}
    {use.movementAlerts?.length ? <p className="ability-alert">检测到 {use.movementAlerts.length} 次位置偏移，工作人员需结合 GPS 精度现场核实。</p> : null}
    {staff && use.status === 'PENDING' ? <div className="ability-actions"><button onClick={() => void run({ type: 'ability_confirm', useId: use.id, result: 'approve' })}>确认生效</button><input aria-label="打回原因" value={reason} onChange={event => setReason(event.target.value)} placeholder="打回原因" /><button disabled={!reason.trim()} onClick={() => void run({ type: 'ability_confirm', useId: use.id, result: 'reject', reason })}>打回并归还卡牌</button></div> : null}
    {!staff && ownTarget && use.status === 'AWAITING_ACK' && !use.acked.includes(session.teamId) ? <button onClick={() => void run({ type: 'ability_ack', useId: use.id })}>接收规则并准备开始</button> : null}
    {!staff && use.casterTeamId === session.teamId && use.status === 'PENDING' ? <button onClick={() => void run({ type: 'ability_cancel', useId: use.id, reason: '玩家取消待确认请求' })}>取消申请</button> : null}
    {!staff && active && (ownTarget || use.number === 1 && use.casterTeamId === session.teamId || use.number === 19 && use.casterTeamId !== session.teamId) && ![3, 5, 8, 15].includes(use.number) ? <form onSubmit={event => { event.preventDefault(); void (async () => { const media = file ? await uploadMedia(file) : undefined; await run({ type: 'ability_submit', useId: use.id, text, media, participants }); setText(''); setFile(null); })().catch(error => { void run({ type: '__client_error', message: String(error) }); }); }}>
      <label>{use.number === 22 ? '提交密钥答案' : use.number === 19 && !ownTarget ? '接触追逐队伍的证据' : '完成说明'}<textarea value={text} onChange={event => setText(event.target.value)} maxLength={4000} required placeholder={use.number === 22 ? '输入答案，提交顺序由服务器记录' : '说明完成情况，供工作人员现场核实'} /></label>
      {use.number !== 22 ? <label>现场图片或短视频（8 MB 内）<input type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" onChange={event => setFile(event.target.files?.[0] ?? null)} /></label> : null}
      {use.number === 20 ? <fieldset><legend>选择三位参与成员</legend>{members.map((member: Entry) => <label key={member.id}><input type="checkbox" checked={participants.includes(member.id)} onChange={event => setParticipants(current => event.target.checked ? [...current, member.id] : current.filter(id => id !== member.id))} />{member.nickname ?? member.username}</label>)}</fieldset> : null}
      <button disabled={!text.trim() || use.number === 20 && participants.length !== 3}>提交给工作人员</button>
    </form> : null}
    {!staff && active && ownTarget && use.number === 15 ? <form onSubmit={event => { event.preventDefault(); void run({ type: 'ability_swap', useId: use.id, peerTeamId: peer, ownTaskId: ownTask, peerTaskId: peerTask }); }}><label>交换队伍<select required value={peer} onChange={event => setPeer(event.target.value)}><option value="">请选择</option>{view.teamChoices.filter((team: Entry) => team.id !== session.teamId && !team.finished).map((team: Entry) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>本队原任务<input required value={ownTask} onChange={event => setOwnTask(event.target.value)} placeholder="任务编号" /></label><label>对方原任务<input required value={peerTask} onChange={event => setPeerTask(event.target.value)} placeholder="任务编号" /></label><button>确认交换下一任务</button></form> : null}
    {evidence.map((item: Entry) => <div className="ability-evidence" key={item.id}><small>{view.teamChoices.find((team: Entry) => team.id === item.teamId)?.name} · {new Date(item.submittedAt).toLocaleTimeString()}</small><p>{item.text}</p>{item.nicknames ? <p>{item.nicknames.map((member: Entry) => member.nickname).join(' / ')}</p> : null}{item.mediaId ? <ProofMedia client={client} id={item.mediaId} /> : null}{staff && item.semanticReview && !item.reviewedBy ? <div className="ability-actions"><input aria-label="中文答案审核原因" value={reason} onChange={event => setReason(event.target.value)} placeholder="中文语义审核依据" /><button disabled={!reason.trim()} onClick={() => void run({ type: 'ability_review', useId: use.id, teamId: item.teamId, evidenceId: item.id, result: 'approve', reason })}>中文语义正确</button><button disabled={!reason.trim()} onClick={() => void run({ type: 'ability_review', useId: use.id, teamId: item.teamId, evidenceId: item.id, result: 'reject', reason })}>答案不符合</button></div> : null}</div>)}
    {staff && ['ACTIVE', 'AWAITING_REVIEW'].includes(use.status) && ![3, 8].includes(use.number) ? <div className="ability-review"><label>结算队伍<select value={reviewTeam} onChange={event => setReviewTeam(event.target.value)}>{use.targets.map((id: string) => <option key={id} value={id}>{view.teamChoices.find((team: Entry) => team.id === id)?.name ?? id}</option>)}</select></label><label>现场审核依据<input value={reason} onChange={event => setReason(event.target.value)} placeholder="填写现场确认结果" /></label>
      {use.number === 6 ? <fieldset><legend>各成员完成的下蹲次数（0–20）</legend>{members.map((member: Entry) => <label key={member.id}>{member.nickname ?? member.username}<input type="number" min={0} max={20} value={counts[member.id] ?? 0} onChange={event => setCounts(current => ({ ...current, [member.id]: Number(event.target.value) }))} /></label>)}</fieldset> : null}
      {use.number === 21 ? <label>确认正确的小数位数<input type="number" min={0} value={digits} onChange={event => setDigits(Number(event.target.value))} /></label> : null}
      {[4, 6, 11, 12, 13, 14, 20, 21].includes(use.number) ? <label><input type="checkbox" checked={inTime} onChange={event => setInTime(event.target.checked)} />已现场确认在规定时间内完成</label> : null}
      <div className="ability-actions">{use.number === 22 ? <button disabled={!reason.trim()} onClick={() => void run({ type: 'ability_settle', useId: use.id, reason })}>按正确答案顺序结算</button> : <><button disabled={!reason.trim() || !!use.results[reviewTeam]} onClick={() => void review('approve')}>现场确认完成</button><button disabled={!reason.trim() || !!use.results[reviewTeam]} onClick={() => void review('reject')}>{use.number === 6 ? '按缺少下蹲数扣分' : '确认未完成 / 违规'}</button></>}<button disabled={!reason.trim()} onClick={() => void run({ type: 'ability_abort', useId: use.id, reason })}>终止此效果</button></div>
    </div> : null}
    {Object.keys(use.results ?? {}).length ? <p className="ability-results">{Object.entries(use.results).map(([id, result]) => `${view.teamChoices.find((team: Entry) => team.id === id)?.name ?? id}：${(result as Entry).points} 分`).join(' · ')}</p> : null}
  </article>;
}

export default function AbilityApp() {
  const [rewardPreview, setRewardPreview] = useState<Entry | null>(null);
  const query = new URLSearchParams(window.location.search);
  const training = query.get('training') === '1' && (import.meta.env.DEV || import.meta.env.VITE_ENABLE_TEST_LAB === 'true');
  const [base, setBase] = useState(import.meta.env.VITE_GAME_API_BASE_URL || import.meta.env.VITE_TEST_API_BASE_URL || window.location.origin);
  const trainingControlKey = useRef('');
  const [gameId, setGameId] = useState(query.get('game') || import.meta.env.VITE_GAME_ID || ''); const [adminKey, setAdminKey] = useState('');
  const [ready, setReady] = useState(false); const [waiting, setWaiting] = useState(false); const [session, setSession] = useState<Session | null>(null); const [client, setClient] = useState<GameClient | null>(null);
  const currentClient = useRef<GameClient | null>(null); const [view, setView] = useState<Entry | null>(null); const [messages, setMessages] = useState<Entry[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [fixture, setFixture] = useState<Entry | null>(null); const [testRole, setTestRole] = useState('host'); const [target, setTarget] = useState(''); const [number, setNumber] = useState(1);
  const [configText, setConfigText] = useState(sampleConfig); const [configNumber, setConfigNumber] = useState(1); const [minutes, setMinutes] = useState(20); const [reward, setReward] = useState(0); const [penalty, setPenalty] = useState(5); const [enabled, setEnabled] = useState(true); const [configReason, setConfigReason] = useState('');
  const [reviewReason, setReviewReason] = useState('');
  const [tracking, setTracking] = useState(false); const [nickname, setNickname] = useState(''); const watch = useRef<number | null>(null); const lastLocation = useRef(0); const sendingLocation = useRef(false);
  const refresh = useCallback(async () => { if (!client) return; const next = await client.request('/state'); const nextMessages = (await client.request('/messages')).messages; if (currentClient.current !== client) return; setView(next); setMessages(nextMessages); }, [client]);
  const advanceTestClock = async (milliseconds: number) => {
    if (!training || !client || !trainingControlKey.current) return; setBusy(true); setError('');
    try { const response = await fetch(`${client.path}/clock`, { method: 'POST', headers: { Authorization: `Bearer ${trainingControlKey.current}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ milliseconds }), signal: AbortSignal.timeout(20000) }); if (!response.ok) throw new Error((await response.json()).message); await refresh(); } catch (error) { setError(String(error)); } finally { setBusy(false); }
  };
  useEffect(() => { if (!client) return; let closed = false; let polling = false; const poll = async () => { if (closed || polling) return; polling = true; try { await refresh(); } catch (error) { if (!closed) setError(String(error)); } finally { polling = false; } }; void poll(); const timer = window.setInterval(() => { void poll(); }, 2000); return () => { closed = true; window.clearInterval(timer); }; }, [client, refresh]);
  const run = async (body: Entry, rethrow = false) => { if (!client) { if (rethrow) throw new Error('尚未连接比赛'); return; } setBusy(true); setError(''); try { if (body.type === '__client_error') throw new Error(body.message); await client.command(body); setNotice('已由服务器确认'); await refresh(); } catch (error) { setError(error instanceof Error ? error.message : String(error)); if (rethrow) throw error; } finally { setBusy(false); } };
  const login = async (role: string, username: string, password: string, id = gameId) => {
    setBusy(true); setError(''); try { const api = validateTestApiBase(base); const response = await fetch(`${api}/api/${training ? 'testing/runs' : 'games'}/${encodeURIComponent(id)}/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role, username, password }), signal: AbortSignal.timeout(20000) }); const data = await response.json(); if (response.status === 401) { setWaiting(true); return; } if (!response.ok) throw new Error(data.message); const nextClient = new GameClient(api, id, data.token, training); currentClient.current = nextClient; setView(null); setMessages([]); setSession(data); setClient(nextClient); setReady(true); } catch (error) { setError(String(error)); } finally { setBusy(false); }
  };
  const create = async () => { setBusy(true); setError(''); try { const api = validateTestApiBase(base); const response = await fetch(`${api}/api/${training ? 'testing/runs' : 'games'}`, { method: 'POST', headers: { Authorization: `Bearer ${adminKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify(training ? { teamCount: 3 } : {}), signal: AbortSignal.timeout(20000) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setGameId(data.id); trainingControlKey.current = training ? adminKey : ''; setAdminKey(''); if (training) { setFixture(data); const credentials = data.credentials.host; await login(credentials.role, credentials.username, credentials.password, data.id); } else { setReady(true); setNotice('比赛已创建，请使用工作人员账号配置任务后开始'); } } catch (error) { setError(String(error)); } finally { setBusy(false); } };
  useEffect(() => {
    if (!tracking || !client || !session?.leader) return;
    const send = (position: GeolocationPosition) => { if (document.visibilityState !== 'visible' || view?.status !== 'RUNNING' || sendingLocation.current || Date.now() - lastLocation.current < 3000) return; lastLocation.current = Date.now(); sendingLocation.current = true; void client.command({ type: 'location', foreground: true, latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, capturedAt: position.timestamp }).catch(error => setError(String(error))).finally(() => { sendingLocation.current = false; }); };
    watch.current = navigator.geolocation.watchPosition(send, error => { setError(`定位失败：${error.message}`); setTracking(false); }, { enableHighAccuracy: true, maximumAge: 0, timeout: 20000 });
    return () => { if (watch.current != null) navigator.geolocation.clearWatch(watch.current); watch.current = null; };
  }, [tracking, client, session?.leader, view?.status]);
  if (waiting) return <WaitingScreen />;
  if (!ready) return <main className="ability-app ability-lobby" id="main-content"><p className="eyebrow">HRG // TACTIC SYSTEM</p><h1>{training ? '能力卡隔离联调' : '连接比赛'}</h1><p>连接比赛后，使用活动账号登录。</p><label>后端地址<input type="url" value={base} onChange={event => setBase(event.target.value)} /></label><label>比赛编号<input value={gameId} onChange={event => setGameId(event.target.value)} /></label><button disabled={busy || !gameId.trim()} onClick={() => { try { validateTestApiBase(base); setReady(true); } catch (error) { setError(String(error)); } }}>进入账号登录</button><details><summary>{training ? '创建隔离测试赛局' : '工作人员创建新比赛'}</summary><label>{training ? '测试访问密钥' : '比赛管理密钥'}<input type="password" autoComplete="off" value={adminKey} onChange={event => setAdminKey(event.target.value)} /></label><button disabled={busy || adminKey.length < 32} onClick={() => void create()}>创建{training ? '测试赛局' : '比赛'}</button><p>密钥只保留在当前页面内存。</p></details>{error ? <p role="alert">{error}</p> : null}<a href="/">返回</a></main>;
  if (!session || !client) return <><LoginScreen onLogin={(role, username, password) => { void login(role, username, password); }} />{error ? <p className="ability-login-error" role="alert">{error}</p> : null}</>;
  if (!view) return <main className="ability-app"><h1>连接比赛中…</h1>{error ? <p role="alert">{error}</p> : null}</main>;
  const staff = session.role === 'staff';
  return <main className="ability-app" id="main-content" aria-busy={busy}><header className="ability-header"><div><p className="eyebrow">HRG // TACTIC SYSTEM {training ? '· 隔离测试' : ''}</p><h1>{staff ? '能力卡控制台' : `${view.team.name} · 能力卡`}</h1><p>{view.status} · 比赛时间 {time(view.elapsedMs)}{!staff ? ` · ${view.team.score} 分` : ''}</p></div><div><button onClick={() => { setTracking(false); currentClient.current = null; setClient(null); setSession(null); setView(null); setMessages([]); }}>退出账号</button><a href="/?test=rules">测试页面</a></div></header>
    {fixture ? <section className="ability-surface"><label>切换测试身份<select value={testRole} onChange={event => setTestRole(event.target.value)}>{Object.keys(fixture.credentials).map(role => <option key={role}>{role}</option>)}</select></label><button disabled={busy} onClick={() => { setTracking(false); const credentials = fixture.credentials[testRole]; void login(credentials.role, credentials.username, credentials.password); }}>切换到所选身份</button><p>隔离赛局使用模拟时钟，点击推进；正式比赛使用实时服务器时钟。</p><div className="ability-actions"><button disabled={busy} onClick={() => void advanceTestClock(30000)}>推进 30 秒</button><button disabled={busy} onClick={() => void advanceTestClock(300000)}>推进 5 分钟</button><button disabled={busy} onClick={() => void advanceTestClock(900000)}>推进 15 分钟</button></div>{fixture.abilityAnswer ? <details><summary>本赛局第22张测试答案（正式比赛不使用）</summary><p>{fixture.abilityAnswer}</p></details> : null}</section> : null}
    <button className="ability-deck-anchor" data-ability-deck onClick={() => document.querySelector('.ability-grid')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'center' })} aria-label={`查看牌库，${view.abilityCards.filter((card: Entry) => card.status === 'AVAILABLE').length}张可用`}><span aria-hidden="true" /><span>牌库 {view.abilityCards.filter((card: Entry) => card.status === 'AVAILABLE').length}</span></button>
    <CardRewards key={`${gameId}:${session.accountId ?? session.teamId}`} view={view} accountId={session.accountId} staff={staff} client={client} refresh={refresh} preview={rewardPreview} closePreview={() => setRewardPreview(null)} />
    <section className="ability-surface" aria-label="半小时发卡"><h2>半小时补给</h2><p>开赛后每 30 分钟，各队随机获得一张能力卡。已发放 {view.periodicAbility?.distributedRounds ?? 0} 轮 · {view.status === 'READY' ? '开赛后开始计时' : view.status === 'FINISHED' ? '比赛已结束' : `下一轮剩余 ${time(view.periodicAbility?.remainingMs ?? 1800000)}${view.status === 'PAUSED' ? '（暂停计时）' : ''}`}</p>{staff ? <><button onClick={() => setRewardPreview({ id: crypto.randomUUID(), number, source: 'preview' })}>预览发卡动效</button><details><summary>自动发卡记录</summary>{(view.periodicAbility?.history ?? []).map((wave: Entry) => <p key={wave.wave}>第 {wave.wave} 轮 · 比赛时间 {time(wave.scheduledElapsedMs)} · {wave.cards.length} 支队伍 · {new Date(wave.grantedAt).toLocaleTimeString()}</p>)}</details></> : null}</section>
    <div className="ability-status" aria-live="polite">{error ? <p role="alert">{error}</p> : notice || '已连接比赛'}{busy ? ' · 正在提交' : ''}</div>
    {staff ? <section className="ability-surface"><div className="ability-actions">{view.status === 'READY' || view.status === 'PAUSED' ? <button disabled={busy} onClick={() => void run({ type: 'transition', status: 'RUNNING' })}>{view.status === 'READY' ? '开始比赛' : '继续比赛'}</button> : null}{view.status === 'RUNNING' ? <button disabled={busy} onClick={() => void run({ type: 'transition', status: 'PAUSED' })}>暂停比赛</button> : null}<button disabled={busy || !['RUNNING', 'PAUSED'].includes(view.status)} onClick={() => void run({ type: 'transition', status: 'FINISHED' })}>结束比赛</button></div><div className="ability-actions"><label>发放队伍<select value={target} onChange={event => setTarget(event.target.value)}><option value="">请选择</option>{view.teamChoices.filter((team: Entry) => !team.finished).map((team: Entry) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>能力卡<select value={number} onChange={event => setNumber(Number(event.target.value))}>{view.abilityCatalog.map((card: Entry) => <option key={card.number} value={card.number}>{card.number}. {card.title}{!card.enabled ? '（已停用）' : ''}</option>)}</select></label><button disabled={busy || !target} onClick={() => void run({ type: 'ability_grant', teamId: target, number, reason: '工作人员现场发放' })}>发放能力卡</button></div>
      <details><summary>调整卡牌分值和时限</summary><label>卡牌<select value={configNumber} onChange={event => { const value = Number(event.target.value); const card = view.abilityCatalog.find((card: Entry) => card.number === value); setConfigNumber(value); setMinutes(card.durationMs / 60000); setReward(card.reward); setPenalty(card.penalty); setEnabled(card.enabled); }}>{view.abilityCatalog.map((card: Entry) => <option key={card.number} value={card.number}>{card.number}. {card.title}</option>)}</select></label><label>时间（分钟）<input type="number" min={0} max={120} step={0.5} value={minutes} onChange={event => setMinutes(Number(event.target.value))} /></label><label>奖励分<input type="number" min={0} value={reward} onChange={event => setReward(Number(event.target.value))} /></label><label>扣分 / 每缺一个下蹲的扣分<input type="number" min={0} value={penalty} onChange={event => setPenalty(Number(event.target.value))} /></label><label><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} />启用此卡</label><label>修改依据<input value={configReason} onChange={event => setConfigReason(event.target.value)} /></label><button disabled={busy || !configReason.trim()} onClick={() => void run({ type: 'ability_configure', number: configNumber, patch: { durationMs: Math.round(minutes * 60000), reward, penalty, enabled }, reason: configReason })}>保存新规则（已生效卡沿用旧规则）</button></details>
      {!training && view.status === 'READY' ? <details><summary>配置正式比赛任务（25 项）</summary><p>填写真实任务标题、说明、分值后才能开始比赛。</p><textarea className="ability-config-json" aria-label="正式任务配置 JSON" value={configText} onChange={event => setConfigText(event.target.value)} /><button disabled={busy} onClick={() => { try { const config = JSON.parse(configText); void run({ type: 'game_configure', ...config, reason: '工作人员配置正式比赛任务' }); } catch { setError('任务配置 JSON 格式有误'); } }}>保存比赛任务</button></details> : null}
    </section> : <section className="ability-surface"><div className="ability-actions"><label>本人的昵称（开赛后锁定）<input value={nickname} onChange={event => setNickname(event.target.value)} maxLength={30} /></label><button disabled={busy || !nickname.trim() || view.status !== 'READY'} onClick={() => void run({ type: 'ability_nickname', nickname })}>保存昵称</button>{session.leader ? <button onClick={() => { if (!navigator.geolocation) setError('此设备不支持定位'); else setTracking(current => !current); }}>{tracking ? '停止实时定位' : '开启实时定位'}</button> : <span>由队长设备上报定位</span>}</div><p>{view.taskPermissions.twoHands ? '下一任务可使用双手' : view.taskPermissions.oneHandOnly ? '当前只能单手操作游戏' : '按活动常规手部规则执行'}{view.taskPermissions.blockedBy.length ? ' · 当前有需优先处理的能力卡，普通任务暂停提交' : ''}</p></section>}
    {view.liveRanking ? <section className="ability-surface"><h2>当前积分与排名</h2><table><thead><tr><th>排名</th><th>队伍</th><th>积分</th></tr></thead><tbody>{view.liveRanking.map((team: Entry) => <tr key={team.teamId}><td>{team.rank}</td><td>{team.name}</td><td>{team.score}</td></tr>)}</tbody></table></section> : null}
    {view.huntLocations?.length || view.locations?.length ? <section className="ability-surface"><h2>队伍定位</h2>{[...(view.locations ?? []), ...(view.huntLocations ?? [])].map((point: Entry, i: number) => <p key={`${point.teamId}-${i}`}>{view.teamChoices.find((team: Entry) => team.id === point.teamId)?.name} · {point.latitude == null ? '尚未上报' : `${point.latitude.toFixed(6)}, ${point.longitude.toFixed(6)}`} · {point.status ?? (point.online ? '在线' : '离线')} {point.latitude != null ? <a href={`https://www.openstreetmap.org/?mlat=${point.latitude}&mlon=${point.longitude}#map=17/${point.latitude}/${point.longitude}`} target="_blank" rel="noreferrer">查看地图</a> : null}</p>)}</section> : null}
    {staff ? <ReservePoolEditor view={view} run={run} /> : null}
    {!staff && view.taskPermissions.phoneTextOnly ? <p className="ability-alert" role="status">爆裂魔法：全员禁言，只能手机打字交流。</p> : null}
    {view.abilityProgress ? <section className="ability-surface" aria-label="全体发卡进度"><h2>全体任务进度</h2><p>累计完成 {view.abilityProgress.completedTasks} 个任务 · 已发放 {view.abilityProgress.distributedRounds} 轮</p><p>每完成 10 个任务，每队获得一张能力卡；下一轮在 {view.abilityProgress.nextAt} 个任务时发放。同队成员共享库存。</p></section> : null}
    {!staff ? <LiveTaskBoard team={view.team} tasks={view.tasks} status={view.status} busy={busy} blocked={!!view.taskPermissions.blockedBy.length} assignment={view.activeAssignment} submissions={view.submissions} submit={body => run(body, true)} /> : null}
    <section><h2>{staff ? '卡牌库存' : '我的能力卡'}</h2><div className="ability-grid">{view.abilityCards.map((card: Entry) => { const definition = view.abilityCatalog.find((item: Entry) => item.number === card.number); return <article className="ability-card" key={card.id}><span className="ability-number">{String(card.number).padStart(2, '0')}</span><h3>{definition.title}</h3><p>{definition.description}</p><small>{statusLabels[card.status]}{staff ? ` · ${view.teamChoices.find((team: Entry) => team.id === card.teamId)?.name}` : ''}</small>{!staff && card.status === 'AVAILABLE' ? <form onSubmit={event => { event.preventDefault(); void run({ type: 'ability_use', instanceId: card.id, targetTeamId: target }); }}><label>目标队伍<select value={target} onChange={event => setTarget(event.target.value)}><option value="">按卡牌规则选择目标</option>{view.teamChoices.filter((team: Entry) => !team.finished && team.id !== session.teamId).map((team: Entry) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><button disabled={busy || !definition.enabled || view.status !== 'RUNNING'}>使用此卡</button></form> : null}</article>; })}</div>{!view.abilityCards.length ? <p>还没有能力卡。开赛后每30分钟、全体每完成10个任务各队会获得一张，也可由工作人员发放。</p> : null}</section>
    <section><h2>生效、待确认与结算记录</h2>{[...view.abilityUses].reverse().map((use: Entry) => <UsePanel key={`${use.id}-${session.accountId ?? session.teamId ?? session.role}`} {...{ use, view, session, client, run }} />)}</section>
    {staff ? <section className="ability-surface"><h2>任务审核队列</h2>{(view.queue ?? []).map((item: Entry, i: number) => <article className="ability-use" key={item.id}><p>{item.teamId} · {item.kind === 'arrival' ? `${item.regionId} 到达确认` : item.taskId}</p><ProofMedia client={client} id={item.mediaId} /><input aria-label="任务审核说明" value={reviewReason} onChange={event => setReviewReason(event.target.value)} placeholder="审核说明（打回必填）" /><div className="ability-actions"><button disabled={busy || i !== 0} onClick={() => void run({ type: 'review', submissionId: item.id, result: 'approve', reason: reviewReason })}>通过审核</button><button disabled={busy || i !== 0 || !reviewReason.trim()} onClick={() => void run({ type: 'review', submissionId: item.id, result: 'reject', reason: reviewReason })}>打回</button></div></article>)}</section> : null}
    <section className="ability-surface"><h2>通知</h2>{[...messages].reverse().slice(0, 30).map((message: Entry) => <p key={message.id}>{message.text} <small>{new Date(message.at).toLocaleTimeString()}</small>{!message.read ? <button onClick={() => void run({ type: 'read_message', messageId: message.id, deviceId: 'ability-web', played: false })}>标记已读</button> : null}</p>)}</section>
  </main>;
}
